import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import { Providers } from './config/providers/Providers'
import './globals.scss'
import './normailze.scss'

const robotoSans = Roboto({
	variable: '--font-roboto-sans',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<body className={`${robotoSans.variable}`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
